std_msgs/Header header

bool enable
bool brake
bool forward
bool reverse

float64 velocity_mps
float64 drive_rpm
float64 steering_angle_rad
float64 steering_angle_deg

float64 accel_time_sec
float64 decel_time_sec

float64 pump_rpm
float64 lift_valve_ma
float64 lower_valve_ma
float64 side_shift_left_valve_ma
float64 side_shift_right_valve_ma
float64 tilt_forward_valve_ma
float64 tilt_backward_valve_ma

bool horn
bool light
